backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "authors"
    label: "Autori"
    folder: "content/authors"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nome", name: "name", widget: "string" }
      - { label: "Cognome", name: "last_name", widget: "string" }
      - { label: "Nickname", name: "nickname", widget: "string" }
      - { label: "Twitter", name: "twitterHandle", widget: "string" }
      - { label: "Email", name: "email", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image" }
  - name: "blog"
    label: "Blog"
    folder: "content/news"
    format: "frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Occhiello", name: "kicker", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sottotitolo", name: "subtitle", widget: "string" }
      - { label: "Data di pubblicazione", name: "date", widget: "datetime" }
      - {
          label: "Copertina",
          name: "image",
          widget: "image",
          choose_url: true,
          media_library: { config: { multiple: false } },
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Galleria",
          name: "gallery",
          widget: "image",
          choose_url: true,
          media_library: { config: { multiple: true } },
        }
      - {
          label: "Autore",
          name: "author",
          widget: "relation",
          collection: "authors",
          search_fields: ["name", "twitterHandle"],
          value_field: "name",
          display_fields: ["nickname"],
        }
